import { metroStations, waterRoutes, landmarks, metroFare } from './transit-data.js';
const $ = s => document.querySelector(s); let malayalam = false;
const mal = {Aluva:'ആലുവ', Vyttila:'വൈറ്റില', 'Ernakulam South':'എറണാകുളം സൗത്ത്', 'Fort Kochi':'ഫോർട്ട് കൊച്ചി', Kakkanad:'കാക്കനാട്', 'JLN Stadium':'ജവഹർലാൽ നെഹ്റു സ്റ്റേഡിയം'};
const choices = [...metroStations, ...waterRoutes.flatMap(r=>r.stops), ...Object.keys(landmarks)];
$('#places').innerHTML = [...new Set(choices)].map(x=>`<option value="${x}"></option>`).join('');
const normal = s => s.trim().toLowerCase();
const match = v => choices.find(x=>normal(x)===normal(v)) || Object.keys(landmarks).find(x=>normal(x)===normal(v));
const toast = t => { $('#toast').textContent=t; $('#toast').classList.add('show'); setTimeout(()=>$('#toast').classList.remove('show'),2500) };
function leg(mode, title, detail, fare, time) { return {mode,title,detail,fare,time} }
function metroLeg(a,b) { const ai=metroStations.indexOf(a), bi=metroStations.indexOf(b), n=Math.abs(ai-bi); return leg('metro','Kochi Metro · Blue Line',`${a} → ${b} · ${n} stations`,metroFare(n),Math.max(6,n*2)); }
function waterLeg(a,b) { const route=waterRoutes.find(r=>r.stops.includes(a)&&r.stops.includes(b)); if(!route)return null; return leg('water',`Water Metro · ${route.name}`,`${a} → ${b} · allow for the next sailing`,route.fare,route.time); }
function resolve(v) { if(metroStations.includes(v)) return {kind:'metro', station:v}; if(landmarks[v]) return landmarks[v].type==='water'?{kind:'water',terminal:landmarks[v].terminal,landmark:v}:{kind:'feeder',station:landmarks[v].station,landmark:v}; if(waterRoutes.some(r=>r.stops.includes(v))) return {kind:'water',terminal:v}; return null; }
function plan(from,to){ const a=resolve(from), b=resolve(to); if(!a||!b)return null; let legs=[];
  if(a.kind==='metro'&&b.kind==='metro') legs=[metroLeg(a.station,b.station)];
  else if(a.kind==='water'&&b.kind==='water'){let w=waterLeg(a.terminal,b.terminal); if(w)legs=[w]; else { legs=[waterLeg(a.terminal,'High Court'),waterLeg('High Court',b.terminal)].filter(Boolean); }}
  else if(a.kind==='metro'&&b.kind==='water'){ const interchange=b.terminal==='Kakkanad'||b.terminal==='Vyttila Mobility Hub'?'Vyttila':'Ernakulam South'; legs=a.station===interchange?[]:[metroLeg(a.station,interchange)]; if(interchange==='Vyttila') legs.push(leg('walk','Vyttila Mobility Hub','Stay within the integrated Metro + KSRTC + Water Metro complex',0,5),waterLeg('Vyttila Mobility Hub',b.terminal)); else {legs.push(leg('walk','Ernakulam South → High Court jetty','Take a short auto-rickshaw or walk to the High Court jetty',0,12),waterLeg('High Court',b.terminal));} }
  else if(a.kind==='water'&&b.kind==='metro'){ const back=plan(to,from); legs=back.legs.reverse(); }
  else { const feeder=a.kind==='feeder'?a:b, other=a.kind==='feeder'?b:a; if(other.kind==='metro'){legs=[leg('feeder','KMRL feeder bus',`${feeder.landmark} ↔ ${feeder.station}`,15,20),metroLeg(feeder.station,other.station)];} else {legs=[leg('feeder','KMRL feeder bus',`${feeder.landmark} ↔ ${feeder.station}`,15,20),...plan(feeder.station,to).legs];} }
  return {legs:legs.filter(Boolean)};
}
function render(from,to){ const route=plan(from,to); if(!route){toast('Choose a Metro station, Water Metro terminal, or listed landmark.');return} const delayed=route.legs.find(l=>(l.title.includes('Vyttila')&&$('#vytDelay').checked)||(l.title.includes('Fort Kochi')&&$('#fortDelay').checked)); const fare=route.legs.reduce((s,l)=>s+l.fare,0), time=route.legs.reduce((s,l)=>s+l.time,0)+(route.legs.filter(l=>l.mode==='water').length*10); $('#routeTitle').textContent=`${from} → ${to}`; $('#legs').innerHTML=route.legs.map((l,i)=>`<article class="leg ${l.mode}"><span class="leg-num">0${i+1}</span><div><b>${l.title}</b><p>${l.detail}</p></div><strong>${l.fare?'₹'+l.fare:'Transfer'}<small>${l.time} min</small></strong></article>`).join(''); $('#totalFare').textContent='₹'+fare; $('#totalTime').textContent=`About ${time} min · Metro runs 6:00 AM–10:30 PM (Sunday from 7:30 AM)`; const d=$('#disruption'); if(delayed){d.hidden=false;d.innerHTML=`<b>Service delay on this Water Metro leg.</b> ${delayed.title.includes('Vyttila')?'Use a feeder bus from Vyttila Mobility Hub to Kakkanad while the sailing recovers.':'Consider a short road connection from Ernakulam South to Fort Kochi; the regular High Court ferry is delayed.'}`;}else d.hidden=true; $('#routeResult').hidden=false; $('#routeResult').scrollIntoView({behavior:'smooth',block:'start'}); localStorage.setItem('metro-connect-last-route',JSON.stringify({from,to})); history.replaceState(null,'',`?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`); }
$('#tripForm').addEventListener('submit',e=>{e.preventDefault();render(match($('#origin').value)||$('#origin').value,match($('#destination').value)||$('#destination').value)});
$('#shareTrip').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Route link copied — ready for WhatsApp.')}catch{toast('Copy this address from your browser to share.')}};
$('#debugToggle').onclick=()=>$('#debug').showModal(); ['#vytDelay','#fortDelay'].forEach(s=>$(s).onchange=()=>{ const p=new URLSearchParams(location.search); if(p.get('from'))render(p.get('from'),p.get('to'))});
$('#languageToggle').onclick=()=>{malayalam=!malayalam;$('#languageToggle').innerHTML=malayalam?'EN <span>മ</span>':'മ <span>EN</span>'; document.querySelectorAll('#places option').forEach(o=>o.textContent=malayalam&&mal[o.value]?mal[o.value]:o.value);toast(malayalam?'പ്രധാന യാത്രാ വിവരങ്ങൾ ഇംഗ്ലീഷിലും ലഭ്യമാണ്':'Key journey details remain in English.');};
const tours={day1:'<b>THE ESSENTIAL LOOP</b><p>Aluva or Edapally → MG Road → Ernakulam South → High Court ferry → Fort Kochi → return via High Court.</p><span>About 7 hours</span><span>From ₹80 + local connections</span>',day2:'<b>THE SLOWER TWO DAYS</b><p>Day 1: Fort Kochi and Mattancherry via High Court. Day 2: Vyttila Mobility Hub → Kakkanad, then explore at an easy pace.</p><span>2 days</span><span>From ₹140 + local connections</span>'}; function tour(k){$('#tourDetail').innerHTML=tours[k]}tour('day1');document.querySelectorAll('.tour').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tour').forEach(x=>x.classList.remove('active'));b.classList.add('active');tour(b.dataset.tour)});
const q=new URLSearchParams(location.search); const saved=JSON.parse(localStorage.getItem('metro-connect-last-route')||'null'); if(q.get('from')){ $('#origin').value=q.get('from');$('#destination').value=q.get('to');render(q.get('from'),q.get('to')); } else if(saved){$('#origin').value=saved.from;$('#destination').value=saved.to;}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');
